
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\pc\Desktop\sign in\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

screen_width = window.winfo_screenwidth()
screen_height = window.winfo_screenheight()
x_coordinate = (screen_width/2) - (990/2)  # 990 is the window width
y_coordinate = (screen_height/2) - (660/2) -40 # 660 is the window height

window.geometry("990x660+{}+{}".format(int(x_coordinate), int(y_coordinate)))


window.configure(bg = "#7129B3")


canvas = Canvas(window, bg = "#7129B3", height = 660, width = 990, bd = 0, highlightthickness = 0, relief = "ridge")

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(831.0, 400.0, image=image_image_1)

canvas.create_rectangle(0.0, 0.0, 618.0, 660.0, fill="#F5F5F5", outline="")

button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button(image=button_image_1,borderwidth=0,highlightthickness=0,command=lambda: print("button_1 clicked"),relief="flat")
button_1.place(x=705.0, y=421.0, width=199.0, height=48.0)

button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
button_2 = Button(image=button_image_2, borderwidth=0, highlightthickness=0, command=lambda: print("button_2 clicked"), relief="flat")
button_2.place(x=200.0, y=421.0, width=210.0, height=48.0)

button_image_3 = PhotoImage(file=relative_to_assets("button_3.png"))
button_3 = Button(image=button_image_3, borderwidth=0, highlightthickness=0, command=lambda: print("button_3 clicked"), relief="flat")
button_3.place(x=361.0, y=387.0, width=129.0, height=19.0)

button_image_4 = PhotoImage(file=relative_to_assets("button_4.png"))
button_4 = Button(image=button_image_4, borderwidth=0, highlightthickness=0, command=lambda: print("button_4 clicked"), relief="flat")
button_4.place(x=331.0, y=517.5, width=54.0, height=19.0)

image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(101.0, 61.0, image=image_image_2)

canvas.create_text(107.0, 40.0, anchor="nw", text="SMS ", fill="#7129B3", font=("Biko_Black", 28 * -1))

canvas.create_text(47.0, 166.0, anchor="nw", text="Welcome Back To SMS ", fill="#000000", font=("Stem-Bold", 45 * -1))

canvas.create_text(685.0, 246.0, anchor="nw", text="New Here?", fill="#F5F5F5" ,font=("Stem-Bold", 45 * -1))

canvas.create_text(166.0, 224.0, anchor="nw", text="sign in to continue to your account  ", fill="#000000", font=("Lionel Text Steam", 25 * -1))

canvas.create_text( 685.0, 321.0, anchor="nw", text="sign up and discover our ", fill="#F5F5F5", font=("Lionel Text Steam", 30 * -1))

canvas.create_text(730.0, 353.0, anchor="nw", text="great services ", fill="#F5F5F5", font=("Lionel Text Steam", 30 * -1))


entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(305.0, 302.0, image=entry_image_1)
entry_1 = Entry(bd=0, bg="#D9D9D9", fg="#000716", highlightthickness=0)
entry_1.place(x=117.0, y=281.0+12, width=376.0, height=20.0)

entry_image_2 = PhotoImage(file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(305.0, 362.0, image=entry_image_2)
entry_2 = Entry( bd=0, bg="#D9D9D9", fg="#000716", highlightthickness=0)
entry_2.place(x=117.0, y=341.0+12 , width=376.0, height=20.0)

canvas.create_text(117.0, 335.0, anchor="nw", text="Password", fill="#000000", font=("Stem-Regular", 12 * -1))

canvas.create_text(117.0, 275.0, anchor="nw", text="Email or Username", fill="#000000", font=("Stem-Regular", 12 * -1))

canvas.create_text(219.0, 520.0, anchor="nw", text="Not a member yet? ", fill="#000000", font=("Stem-Regular", 12 * -1))

canvas.create_text(212.0, 606.0, anchor="nw", text="© 2023 SMS , All Rights Reserved", fill="#000000", font=("Montserrat Regular", 11 * -1))

canvas.create_text(214.0, 619.0, anchor="nw", text="  By signing up, I agree to SMS’s ", fill="#000000", font=("Montserrat Regular", 11 * -1))

canvas.create_text(250.0, 632.0, anchor="nw", text="Terms of Service", fill="#242371", font=("Montserrat Regular", 11 * -1))
window.resizable(False, False)
window.mainloop()
