
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\pc\Desktop\tkinter\loginregis\loginRegistrationSystem\home page\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def aboutus_page():
    window.destroy()
    import aboutus

def signup_page():
    window.destroy()
    import signupfinal

def signin_page():
    window.destroy()
    import signinpage1

window = Tk()
screen_width = window.winfo_screenwidth()
screen_height = window.winfo_screenheight()
x_coordinate = (screen_width/2) - (990/2)  # 990 is the window width
y_coordinate = (screen_height/2) - (660/2) -40
# 660 is the window height
window.geometry("990x660+{}+{}".format(int(x_coordinate), int(y_coordinate)))

window.configure(bg = "#FFFFFF")


canvas = Canvas(window, bg = "#FFFFFF",height = 660, width = 990, bd = 0, highlightthickness = 0, relief = "ridge")

canvas.place(x = 0, y = 0)
canvas.create_rectangle( 0.0,  0.0, 990.0,  660.0, fill="#24035E", outline="")

button_image_1 = PhotoImage( file=relative_to_assets("button_1.png"))
button_1 = Button( image=button_image_1, borderwidth=0, highlightthickness=0, command=signin_page, relief="flat")
button_1.place( x=566.0, y=59.0, width=56.0, height=28.0)

button_image_2 = PhotoImage( file=relative_to_assets("button_2.png"))
button_2 = Button( image=button_image_2, borderwidth=0, highlightthickness=0, command=aboutus_page, relief="flat")
button_2.place( x=649.0, y=59.0, width=84.0, height=28.0)

button_image_3 = PhotoImage( file=relative_to_assets("button_3.png"))
button_3 = Button( image=button_image_3, borderwidth=0, highlightthickness=0, command=signup_page, relief="flat")
button_3.place( x=758.0, y=59.0, width=86.0, height=28.0)

button_image_4 = PhotoImage(file=relative_to_assets("button_4.png"))
button_4 = Button(image=button_image_4, borderwidth=0, highlightthickness=0, command=lambda: print("button_4 clicked"), relief="flat")
button_4.place(x=867.0, y=59.0, width=78.0, height=28.0)

image_image_1 = PhotoImage( file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image( 749.0, 349.0, image=image_image_1)

image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image( 132.0, 98.0, image=image_image_2)

canvas.create_text( 58.0, 599.0, anchor="nw", text="©️ 2023 SMS. All Rights Reserved   ", fill="#FFFFFF", font=("Montserrat Regular", 14 * -1))

canvas.create_text(774.0, 599.0, anchor="nw", text="Designed by AKARI", fill="#FFFFFF", font=("Montserrat Regular", 14 * -1))

canvas.create_text(156.0, 68.0, anchor="nw", text="SMS", fill="#FFFFFF", font=("Biko", 40 * -1))

canvas.create_text(49.0, 228.0, anchor="nw", text="System", fill="#FFFFFF", font=("Poppins Bold", 30 * -1))

canvas.create_text(49.0, 193.0, anchor="nw", text="Student Management \n", fill="#FFFFFF", font=("Poppins Bold", 30 * -1))

canvas.create_text(54.0, 465.0, anchor="nw", text="\"Optimize, Manage, Succeed.\"" , fill="#FFFFFF", font=("Poppins ExtraLight Italic", 20 * -1))

canvas.create_text( 54.0, 408.0, anchor="nw", text="friendly platform.\n", fill="#FFFFFF", font=("Poppins Medium", 20 * -1))

canvas.create_text( 54.0, 356.0, anchor="nw", text="Effortlessly manage student data and \n",fill="#FFFFFF", font=("Poppins Medium", 20 * -1))

canvas.create_text(49.0, 381.0, anchor="nw", text=" improve outcomes with our user-\n", fill="#FFFFFF", font=("Poppins Medium", 20 * -1))

button_image_5 = PhotoImage(file=relative_to_assets("button_5.png"))
button_5 = Button(image=button_image_5, borderwidth=0, highlightthickness=0, command=lambda: print("button_5 clicked"), relief="flat")
button_5.place(x=52.0, y=310.0, width=266.0, height=12.0)

window.resizable(False, False)
window.mainloop()
